let x = 100;
let nAme = "Liza Diata";
let isValue = (x>=99);
let arr=['sibuyas, kamatis, bawang'];
let y= null;
console.log(`Number: ${x} `, typeof(x));
console.log(`Hi this is me ${nAme} `, typeof(nAme));
console.log(`Boolean: ${isValue} `, typeof (isValue)); 
console.log(`Array: ${arr} `,typeof(arr));
console.log(`Null Value: ${y} `,typeof (y));